AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2
  Exclude:
    - bin/**/*
    - db/schema.rb
    - config/**/*.rb
    - Rakefile
    - vendor/**/*

Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - app/**/concerns/**/*.rb

Style/SignalException:
  EnforcedStyle: semantic

Style/Documentation:
  Exclude:
    - config/**/*.rb
    - db/migrate/*.rb
