default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  host: localhost
  port: 25432
  username: postgres
  password: zee_api
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: zee_api_development

test:
  <<: *default
  database: zee_api_test

production:
  <<: *default
  database: zee_api_production
