#!/bin/bash

function show_instructions {
    echo "This will install native dependencies and infrastructure for the project."
    echo "This will also uninstall Ubuntu's Docker and install Docker CE. If any of"
    echo "that might present a problem for you, please review the bootstrap script"
    echo "and take matters into your own hands."
    echo
}

function ask_to_continue {
    while true
    do
        read -p "You will be prompted for your sudo password. Continue (Y/N)? " answer

        # (2) handle the input we were given
        case $answer in
            [yY]* ) echo "Moving on!";
                    break;;

            [nN]* ) exit;;

            * )     echo "Enter Y or N, please.";;
        esac
    done
}

function install_docker {
         echo "Remove Ubuntu's Docker... "
         sudo apt-get remove -y docker docker-engine docker.io containerd runc
         echo "done."

         echo -n "Setup Docker CE... "
         sudo apt-get install -y\
              apt-transport-https \
              ca-certificates \
              curl \
              gnupg-agent \
              software-properties-common

         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

         sudo add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"

         sudo apt-get update
         echo "done."

         echo -n "Install Docker CE... "
         sudo apt-get install -y docker-ce docker-ce-cli containerd.io
         echo "done."
}

function install_dependencies {
    echo -n "Installing native dependencies... "
    sudo apt-get install -y \
         build-essential \
         libpq-dev
    echo "done."
}

show_instructions
ask_to_continue
install_docker
install_dependencies
